### ISSUE TITLE
Просьба проверить домашнее задание

### ISSUE THREAD

**Issue by a1h05** [a1h05/typing-practice#1]
@JSMonk привет! Проверьте, пожалуйста, ДЗ. Ветка https://github.com/a1h05/typing-practice/tree/homework-task-types

**Comment by JSMonk** [comment]
Здравствуйте, Антон.
Хочу заметить, что очень хорошая работа.
Давайте немного подрефакторим и будем великолепно.
1. Вот [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...a1h05:homework-task-types#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR43) Вы повторяете логику [`UserService#getAllUsers`](https://github.com/JSMonk/typing-practice/blob/homework-task/src/services/user-service.ts#L12). Давайте поиском по пользователям будет заниматься `UserService`, а мы будем подключать `UserService` как зависимость `LoginService` (также как мы уже делали с [`OperationService`](https://github.com/JSMonk/typing-practice/blob/homework-task/src/services/operation-service.ts#L19)).
2. Давайте сделаем [синхронные операции](https://github.com/JSMonk/typing-practice/compare/homework-task...a1h05:homework-task-types#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR31) - синхронными.
3. [Вот здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...a1h05:homework-task-types#diff-096045fcc15e15c86099818c37598b123dd4e9cf6d9d265213b0f1c4b6858808R10) можно сделать еще более наглядно и декларативно. Поиграйтесь с [данными примером](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgJRAGzjA3jAQQBEBZASQDkYAaGEgeSIFE0CAVetWgYQBkymFNjAC+AKFCRYCFDHoAHOACcAhlACW4PDACqABSLsmAfQ7G+AoTV0Gjp+sYbNWHLjcNsTZ4uSrixUACeioQAJsjqYDAAvNpKWHAAXOgJAHQ+lKIA3AHBONyY6giwsfjx2MkY2KkWgsIiOUEhJCChymogSjFxCZVpTizsnNliuSE6EMrdBOGRMAA+MAVFYLCLLW2qUJ2NeTB6SuoAburYAOZwoRNTsTMRUeut7dtKOWIA9O8wgDgggHwggGwggF4QX4wQCiIIABEEADCCAwAcIIAhEEAMiAwQBcIJDkTBfnDACwggFYQQDcIAjAYBhEEAciAo36AwAiIDDAMwgRKhgDEQGFkwBMICi0b9ADwgAFo4SDKZDAJwgeJxEnA0EIADUCGReAQAEK8Ez0PSDNhkegUADK3VwYhgBpgAG0qnAavw6gBdZJ6w1242m9KkSjW42W6j6+0Gk39Rhqziuo3uz1en3VWpCQOWkOiD12sNmgYuAM2mPxx0ZChRuNeh2+5xDNCBhTPTRgVL6DxeBwRtjB3N58MWyPJI0lrZliu2Tz2Rx+5NFmMiHPejPOrOphsJp2+YuKDvgLtV3tJwv13PT1euOelxeVuxmWu0dtqTv7nvecfr0OO2s7hfl8-VvsF7dDsQiGAqCAwSTQN4AGaIGAwAaFoFxQAQRwqKcKgAEbYCeYGQAAPGgACM8AAB5QAgoQ-qatBoAATNhuFgPhKTYAAfAAFIgkxKMk1xdAAZD0FToJhw6-ogShKMULHJAcxynHAFxXIxMDsWUvToKRIgAJR4J6AlQHxUQENKsoKkqxgqmqGrakawB8QJqwsak5RwJaRoMcoVkJJaOT+H+sAqN0EFQTBmDwYh86nuKtGyZxjpbsMPEhUkVFmpmoiKVkQA).
4. Если Вы сделаете пункт 3 - то определение типа функции [`getAvailableOperations`](https://github.com/JSMonk/typing-practice/compare/homework-task...a1h05:homework-task-types#diff-096045fcc15e15c86099818c37598b123dd4e9cf6d9d265213b0f1c4b6858808R64) будет описывать более строгую договоренность нежеди просто возвращать какие-то операции (Readonly<Operation[]>)

**Comment by a1h05** [comment]
@JSMonk, спасибо за ревью. 

Залил апдейт, посмотрите, пожалуйста.

**Comment by JSMonk** [comment]
Гуд, принято.
Хорошая работа 👍
